"""Phase 16 local desktop product shell."""

from luna.desktop.bootstrap import build_local_desktop_controller
from luna.desktop.brand import (
    BRAND_ASSET_DIR,
    LUNA_BRAND_BLUE,
    LUNA_BRAND_DARK_PANEL,
    LUNA_BRAND_NEAR_BLACK,
    LUNA_BRAND_SOFT_WHITE,
    LUNA_DARK_BRAND_ASSETS,
    LUNA_ICON_SIZES,
    LUNA_LIGHT_BRAND_ASSETS,
    LunaBrandAssets,
    LunaBrandPlacement,
    LunaBrandTheme,
    luna_brand_assets,
    luna_empty_state_brand_asset,
    luna_sidebar_brand_asset,
)
from luna.desktop.controller import DesktopShellController
from luna.desktop.gateway import DesktopCommandGateway
from luna.desktop.layout import DesktopLayout, DesktopLayoutMode, desktop_layout_for_width
from luna.desktop.models import (
    DesktopAccessMode,
    DesktopApproval,
    DesktopComposerDraft,
    DesktopNotificationCard,
    DesktopResourceSummary,
    DesktopScheduleCard,
    DesktopSection,
    DesktopShellSnapshot,
    DesktopTaskCard,
    DesktopTaskState,
    DesktopTone,
)
from luna.desktop.presenter import (
    notification_card,
    resource_summary,
    schedule_card,
    task_card,
    task_cards,
)
from luna.desktop.theme import (
    DARK_THEME_TOKENS,
    LUNA_DARK_PALETTE,
    LUNA_LIGHT_PALETTE,
    THEME_TOKENS,
    LunaPalette,
)
from luna.desktop.tk_shell import launch_desktop_shell

__all__ = [
    "BRAND_ASSET_DIR",
    "DARK_THEME_TOKENS",
    "LUNA_BRAND_BLUE",
    "LUNA_BRAND_DARK_PANEL",
    "LUNA_BRAND_NEAR_BLACK",
    "LUNA_BRAND_SOFT_WHITE",
    "LUNA_DARK_BRAND_ASSETS",
    "LUNA_DARK_PALETTE",
    "LUNA_ICON_SIZES",
    "LUNA_LIGHT_BRAND_ASSETS",
    "LUNA_LIGHT_PALETTE",
    "THEME_TOKENS",
    "DesktopAccessMode",
    "DesktopApproval",
    "DesktopCommandGateway",
    "DesktopComposerDraft",
    "DesktopLayout",
    "DesktopLayoutMode",
    "DesktopNotificationCard",
    "DesktopResourceSummary",
    "DesktopScheduleCard",
    "DesktopSection",
    "DesktopShellController",
    "DesktopShellSnapshot",
    "DesktopTaskCard",
    "DesktopTaskState",
    "DesktopTone",
    "LunaBrandAssets",
    "LunaBrandPlacement",
    "LunaBrandTheme",
    "LunaPalette",
    "build_local_desktop_controller",
    "desktop_layout_for_width",
    "launch_desktop_shell",
    "luna_brand_assets",
    "luna_empty_state_brand_asset",
    "luna_sidebar_brand_asset",
    "notification_card",
    "resource_summary",
    "schedule_card",
    "task_card",
    "task_cards",
]
