"""Typed, side-effect-free status contract declarations."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class StatusFactKind(StrEnum):
    DECLARED = "DECLARED"
    DERIVED = "DERIVED"


@dataclass(frozen=True, slots=True)
class StatusFact:
    key: str
    kind: StatusFactKind
    declared_value: str | None = None


def declared(key: str, value: str) -> StatusFact:
    return StatusFact(key, StatusFactKind.DECLARED, value)


def derived(key: str) -> StatusFact:
    return StatusFact(key, StatusFactKind.DERIVED)


STATUS_FACTS = (
    declared("phase", "19"),
    declared("status", "IMPROVEMENT_GATE_IMPLEMENTED_UNVERIFIED"),
    declared("tool_dispatcher", "deny_by_default"),
    derived("registered_tools"),
    declared("workspace_writes", "snapshot_first_atomic"),
    declared("rollback", "sha256_verified"),
    declared("process_execution", "exact_argv_owner_approved"),
    declared("shell_parsing", "disabled"),
    declared("file_delete", "disabled"),
    declared("network_tools", "disabled"),
    declared("audit_log", "append_only_jsonl_sha256_chain"),
    declared("output_logs", "redacted_content_addressed"),
    declared("completion_verifier", "deterministic_requirement_evidence_gate"),
    declared("verified_complete", "gate_only"),
    declared("checkpoint_store", "sqlite_wal_atomic"),
    declared("resume_guard", "revision_workspace_environment"),
    declared("blind_replay", "blocked"),
    declared("memory_store", "sqlite_wal_scoped"),
    declared("memory_policy", "candidate_verify_commit_or_reject"),
    declared("model_inference_as_fact", "blocked"),
    declared("plaintext_secrets_in_memory", "blocked"),
    declared("one_off_preference_persistence", "blocked"),
    declared("memory_expiry_and_supersede", "enabled"),
    declared("identity_profile", "versioned_runtime_owned"),
    declared("hard_coded_user_profile", "absent"),
    declared("final_report", "gate_bound_and_audited"),
    derived("autonomy_levels"),
    declared("free_research", "separate_expiring_contract_required"),
    declared("model_authority_escalation", "blocked"),
    declared("fixed_eval_suite", "revision_locked_sha256"),
    declared("regression_runner", "deterministic_comparable_metrics"),
    declared("release_gate", "runtime_owned_thresholds"),
    declared("critical_false_success", "zero_required"),
    declared("known_limitations", "publication_required"),
    declared("runtime_request", "source_actor_scope_budget_bound"),
    declared("actor_authority", "runtime_verified_model_cannot_grant"),
    declared("runtime_budget", "read_only_default"),
    declared("task_fingerprint", "deterministic_duplicate_candidate"),
    declared("runtime_outcome", "task_state_and_completion_gate_bound"),
    derived("context_layers"),
    declared("context_budget", "per_layer_and_overall_runtime_enforced"),
    declared("context_unobserved", "excluded_never_implied"),
    declared("context_secrets", "blocked_or_redacted_before_model_view"),
    declared("context_memory", "verified_data_only"),
    declared("context_freshness", "explicit_and_deterministic"),
    declared("action_proposal", "untrusted_no_authority"),
    declared("tool_selection", "two_stage_runtime_owned"),
    declared("structured_denial", "blocked_observation"),
    declared("side_effect_proposals", "max_one_per_iteration"),
    declared("selection_execution_boundary", "dispatcher_required"),
    declared("failure_taxonomy", "structured_runtime_owned"),
    declared("blind_retry", "changed_basis_required"),
    declared("minimal_change", "path_and_line_budget_enforced"),
    declared("scope_creep", "observed_change_cannot_expand_approval"),
    declared("workspace_isolation", "snapshot_low_medium_worktree_high_critical"),
    declared("worktree_downgrade", "blocked"),
    declared("policy_agent_loop", "single_identity_authoritative_task_state"),
    declared("side_effect_journal", "write_ahead_sqlite_fence"),
    declared("runtime_observations", "durable_data_only_context"),
    declared("effective_workspace", "isolated_root_persists_across_steps"),
    declared("safe_control", "suspend_cancel_at_runtime_boundaries"),
    declared("resume_side_effect_replay", "ambiguous_started_action_blocked"),
    declared("completion_handoff", "phase12f_gate_bound"),
    declared("evidence_strength", "runtime_owned_weak_moderate_strong_deterministic"),
    declared("evidence_disagreement", "unresolved_conflict_blocks_success"),
    declared("evidence_store", "sqlite_wal_hash_checked"),
    declared("finalization", "gate_report_terminal_checkpoint"),
    declared("learning_candidates", "review_required_no_auto_commit"),
    declared("runtime_conformance_suite", "revision_locked_sha256"),
    derived("runtime_e2e_cases"),
    declared("scope_path_preflight", "deny_before_dispatch"),
    declared("phase12_acceptance", "component_plus_runtime_e2e"),
    declared("model_compatibility", "required_text_single_tool_json_args"),
    declared("model_backend_failures", "structured_provider_neutral"),
    declared("model_failure_retry", "never_blind"),
    declared("model_rollout", "blocked_shadow_canary_active_runtime_owned"),
    declared("shadow_authority", "none"),
    declared("canary_allocation", "deterministic_task_bucket"),
    declared("rollout_tripwires", "false_success_authority_backend_invalid_turn"),
    declared("live_probe", "loopback_only_no_rollout_authority"),
    declared("research_gateway", "runtime_owned_read_only"),
    declared("research_network", "explicit_runtime_and_policy_authority"),
    declared("research_domains", "allow_deny_fail_closed"),
    declared("research_budget", "request_elapsed_token_bound"),
    declared("research_provenance", "publisher_url_retrieval_sha256"),
    declared("research_citations", "current_claims_source_bound"),
    declared("research_injection", "data_only_no_runtime_control"),
    declared("research_external_actions", "forbidden"),
    declared("research_memory", "review_required_no_auto_commit"),
    declared("research_document_evidence", "moderate_non_terminal"),
    declared("operations_store", "sqlite_wal_shared_transaction_boundary"),
    declared("durable_queue", "idempotent_priority_eligible"),
    declared("queue_dispatch_fence", "pre_runtime_no_blind_replay"),
    declared("resource_manager", "capacity_only_no_authority_grant"),
    declared("resource_stale_lease", "blocks_capacity_until_reconciled"),
    declared("scheduler", "utc_one_shot_fixed_interval_materialize_only"),
    declared("scheduler_free_research_clone", "blocked"),
    declared("notifications", "local_outbox_runtime_outcome_bound"),
    declared("notification_external_delivery", "disabled"),
    declared("desktop_shell", "local_light_first_conversation_workspace"),
    declared("desktop_theme", "white_graphite_soft_surface_luna_blue"),
    declared("desktop_default_authority", "read_only"),
    declared("desktop_write_authority", "explicit_bounded_user_approval"),
    declared("desktop_command_path", "runtime_request_then_durable_queue"),
    declared("desktop_direct_tool_or_model_call", "forbidden"),
    declared("desktop_completion_label", "runtime_outcome_verification_bound"),
    declared("desktop_details", "task_evidence_verification_resource_visible"),
    declared("desktop_notifications", "local_outbox_only"),
    declared("desktop_renderer", "tkinter_lazy_loaded"),
    declared("discord_gateway", "verified_transport_runtime_bound"),
    declared("discord_role_source", "configured_gateway_mapping_only"),
    declared("discord_channels", "configured_allowlist_only"),
    declared("discord_autonomy_escalation", "blocked"),
    declared("discord_project_write", "disabled"),
    declared("discord_process_terminal", "disabled"),
    declared("discord_network_authority", "disabled"),
    declared("discord_model_unavailable", "durable_queue"),
    declared("discord_rate_limit", "role_bound_fixed_window"),
    declared("discord_moderation", "ingress_only_no_external_action"),
    declared("discord_audit", "append_only_content_digest_no_raw_message"),
    declared("voice_gateway", "verified_local_session_runtime_bound"),
    declared("voice_stt_tts", "provider_neutral_adapter_contracts"),
    declared("voice_transcript_view", "explicit_session_bound"),
    declared("voice_low_risk_command", "direct_confirmation_required"),
    declared("voice_high_risk", "double_confirmation_then_approval_review"),
    declared("voice_spoken_authority", "none"),
    declared("voice_project_write", "disabled"),
    declared("voice_process_terminal", "disabled"),
    declared("voice_network_authority", "disabled"),
    declared("voice_interrupt_cancel", "predispatch_safe_control"),
    declared("voice_tts_persona", "not_locked_in_phase18"),
    declared("voice_audit", "append_only_transcript_digest_no_raw_audio"),
    declared("phase19_trace", "observable_structured_no_raw_hidden_cot"),
    declared("phase19_failure_taxonomy", "cognitive_tool_execution_verification"),
    declared("phase19_tool_normalization", "semantic_mapping_no_wrapper_authority"),
    declared("phase19_split", "task_repository_trajectory_grouped_leak_free"),
    declared("phase19_held_out", "explicit_unseen_task_families"),
    declared("phase19_training_transform", "target_only_loss_reviewed_data_only"),
    declared("phase19_training_run", "not_executed_by_foundation"),
    declared("phase19_uncertainty", "confidence_evidence_bound"),
    declared("phase19_self_correction", "changed_basis_not_blind_retry"),
    declared("phase19_baseline", "frozen_pretraining_dimension_comparison"),
    declared("phase19b_eval_suite", "heldout_ood_revision_locked_sha256"),
    declared("phase19b_regression_suite", "case_inventory_revision_locked"),
    declared("phase19b_contamination", "exact_source_and_family_overlap_checked"),
    declared("phase19b_evaluator", "versioned_independent_candidate_cannot_self_judge"),
    declared("phase19b_release_comparison", "like_for_like_no_promotion_authority"),
    declared("phase19b_real_benchmark_run", "not_executed_by_governance_foundation"),
    declared("phase19c_learning_integrity", "frozen_policy_observable_evidence_only"),
    declared("phase19c_shortcut_learning", "matched_observational_slice_gap_checked"),
    declared("phase19c_benchmark_gaming", "frozen_case_identity_exposure_blocked"),
    declared("phase19c_evaluator_gaming", "identity_exposure_and_disagreement_checked"),
    declared("phase19c_proxy_optimization", "proxy_gain_with_governed_regression_blocked"),
    declared("phase19c_confirmation_bias", "ignored_contradictory_evidence_blocked"),
    declared("phase19c_self_confirmation", "independent_support_required"),
    declared("phase19c_overfitting", "train_heldout_ood_gap_checked"),
    declared("phase19c_promotion_authority", "none"),
    declared("phase19c_real_training_run", "not_executed_by_integrity_foundation"),
    declared("phase19d_counterfactual", "controlled_replay_or_sandbox_only"),
    declared("phase19d_unexecuted_alternative", "hypothesis_only"),
    declared("phase19d_comparability", "same_case_revision_environment"),
    declared("phase19d_evidence", "independent_observation_required"),
    declared("phase19d_safety", "critical_regression_zero_tolerance"),
    declared("phase19d_generalized_causal_authority", "none"),
    declared("phase19d_promotion_authority", "none"),
    declared("phase19d_real_training_run", "not_executed_by_counterfactual_foundation"),
    declared("phase19e_sft_corpus", "normalized_train_only_target_only_loss"),
    declared("phase19e_tool_schema", "luna_canonical_only"),
    declared("phase19e_privacy_normalization", "required"),
    declared("phase19e_initial_mix", "implementation_primary_judge_harness_bounded"),
    declared("phase19e_training_spec", "base_trainer_corpus_hyperparameters_sha256_locked"),
    declared("phase19e_external_training_receipt", "execution_and_artifact_evidence_required"),
    declared("phase19e_trained_candidate", "unpromoted"),
    declared("phase19e_runtime_authority", "none"),
    declared("phase19e_promotion_authority", "none"),
    declared("phase19e_real_training_run", "not_executed_by_repository_governance"),
    declared("phase19f_improvement_gate", "paired_confidence_thresholds_multi_metric"),
    derived("phase19f_critical_regression"),
    declared("phase19f_candidate_evidence", "phase19e_receipt_and_artifact_required"),
    derived("phase19f_decisions"),
    derived("phase19f_runtime_authority"),
    declared("phase19f_real_candidate_evaluation", "not_executed_without_trained_candidate"),
    declared("phase19f_release_action_execution", "not_performed_by_gate"),
    derived("c002_capability_lineage"),
    declared("c002_automatic_roadmap_mutation", "disabled"),
    declared("c002_runtime_authority", "none"),
    derived("c001_adaptive_retrieval"),
    declared("c001_contradictory_evidence", "stop_and_reinspect"),
    declared("c001_automatic_memory_commit", "disabled"),
    declared("c001_runtime_authority", "none"),
    derived("c003_experience_distillation"),
    declared("c003_cross_case_generalization", "evidence_bounded"),
    declared("c003_model_self_certification", "blocked"),
    declared("c003_automatic_memory_commit", "disabled"),
    declared("c003_runtime_training_promotion_authority", "none"),
    derived("c007_debugging_transfer"),
    declared("c007_repair_and_diagnosis_metrics", "required"),
    declared("c007_changed_basis_replan", "explicit_when_initial_repair_fails"),
    declared("c007_runtime_training_memory_promotion_authority", "none"),
)
